[package]
name = "jack-sys"
version = "0.0.2"
authors = ["Patrick Reisert"]
description = "Low-level binding to the JACK audio API."
repository = "https://github.com/Boddlnagg/jack-sys"
license = "MIT"

[dependencies]
libc = "*"